openai_api_key: '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'

tmdb_access_token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZGJhYjU5MGM3ZWFjYTA3ZWJlNjI1OTc0YTM3YWQ5MiIsInN1YiI6IjY1MmNmODM3NjYxMWI0MDBmZmM3MDM5OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.McsK4Wm5XnRSDLn62Jhy787YUAwZcQz0X5qzkGuLe_s

spotipy_client_id: "8cebf17189514287a4c9a25a4ac069a6"
spotipy_client_secret: "ab8967dacb50447d975e98f4e8b8aa95"
spotipy_redirect_uri: "https://scholar.google.com/citations?user=4UlXbpQAAAAJ&hl=en"